### ISSUE TITLE
How to trigger the methods (SetTxHandler and SubscribeS6F11)

### ISSUE THREAD

**Issue by WeiJim** [mkjeff/secs4net#7]
In the Driver.cs file of MWN01 project, I has been build methods (SetTxHandler and SubscribeS6F11) of EAP, But I don't know how to trigger.
Could you give me a tip?  
Thanks,

**Comment by mkjeff** [comment]
Yep, Tx handler from TCS, it can not work for now. 
Because I removed an IPC component. it will handle the message sent from the other systems.
The commented code in [here](https://github.com/mkjeff/secs4net/blob/master/secs4net/Core/EAPHost/MainForm.cs#L543-L568)
I would like to try another way for system integration. like, HTTP or other RPC interfaces.

SubscribeS6F11 is not working because .net remoting will be deprecated also(.net core).

At present, I still work on improvement of SecsCore project.

**Comment by WeiJim** [comment]
Thanks
